//
//  MessagesViewController.swift
//  Nerdle MessagesExtension
//
//  Created by Andrew Carvajal on 7/24/22.
//

import UIKit
import Messages
import MessageUI

class MessagesViewController: MSMessagesAppViewController {
    
    // MARK: - Properties
    private var logoImageView: UIImageView?
    private var gridView: GridView?
    private var sendButton: UIButton?
    
    // MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        addLogo()
        addGridView()
        addSendButton()
    }
    
    
    // MARK: - Private Methods
    private func addLogo() {
        logoImageView = UIImageView(frame: Frame.Logo.frame(view.frame))
        logoImageView?.image = UIImage(named: "nerdle.png")
        view.addSubview(logoImageView!)
    }
    
    private func addGridView() {
        gridView = GridView(frame: Frame.Grid.frame(view.frame))
        view.addSubview(gridView!)
    }
    
    private func addSendButton() {
        sendButton = UIButton(frame: Frame.SendButton.frame(view.frame))
        sendButton?.addTarget(self, action: #selector(didTapSendButton(sender:)), for: .touchUpInside)
        sendButton?.layer.cornerCurve = .continuous
        sendButton?.layer.cornerRadius = 5
        let largeConfig = UIImage.SymbolConfiguration(pointSize: 42, weight: .bold, scale: .medium)
        let image = UIImage(systemName: "arrow.up.circle.fill", withConfiguration: largeConfig)!
        sendButton?.setImage(image, for: .normal)
        sendButton?.setTitleColor(.white, for: .normal)
        view.addSubview(sendButton!)
    }
    
    @objc
    private func didTapSendButton(sender: UIButton) {
        activeConversation?.send(composeMessage(), completionHandler: { error in
            if let error = error {
                print("Error: \(error.localizedDescription)")
            }
        })
    }
    
    private func composeMessage() -> MSMessage {
        let session = activeConversation?.selectedMessage?.session
        let message = MSMessage(session: session ?? MSSession())
        
        let components = NSURLComponents()
        components.queryItems = [
            URLQueryItem(name: "answer", value: GameModel.shared.answer),
            URLQueryItem(name: "guess1", value: GameModel.shared.firstGuess),
            URLQueryItem(name: "guess2", value: GameModel.shared.secondGuess),
            URLQueryItem(name: "guess3", value: GameModel.shared.thirdGuess),
            URLQueryItem(name: "guess4", value: GameModel.shared.fourthGuess),
            URLQueryItem(name: "guess5", value: GameModel.shared.fifthGuess),
            URLQueryItem(name: "guess6", value: GameModel.shared.sixthGuess),
        ]
        message.url = components.url!

        let layout = MSMessageTemplateLayout()
        layout.image = UIImage(named: "nerdle.png")
        layout.caption = "Nerdle"
        layout.subcaption = "It's your turn!"
        layout.trailingSubcaption = "🟨🟩⬜️⬜️⬜️"

        message.layout = layout
        return message
    }
    
    
    // MARK: - Conversation Handling
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
        print("willBecomeActive(with conversation: MSConversation)")
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dismisses the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
        print("didResignActive(with conversation: MSConversation)")
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
        guard let url = message.url else {
            print("Could not get URL from MSMessage.")
            return
        }
        guard let components = NSURLComponents(url: url, resolvingAgainstBaseURL: false) else {
            print("Could not create NSURLComponents from MSMessage URL.")
            return
        }
        
        if let queryItems = components.queryItems {
            
            var firstGuess: String?
            var secondGuess: String?
            var thirdGuess: String?
            var fourthGuess: String?
            var fifthGuess: String?
            var sixthGuess: String?
            
            for queryItem in queryItems {
                if let value = queryItem.value {
                    switch queryItem.name {
                    case "answer":
                        GameModel.shared.answer = value
                    case "guess1":
                        if !value.isEmpty {
                            GameModel.shared.firstGuess = value
                            firstGuess = value
                        }
                    case "guess2":
                        if !value.isEmpty {
                            GameModel.shared.secondGuess = value
                            secondGuess = value
                        }
                    case "guess3":
                        if !value.isEmpty {
                            GameModel.shared.thirdGuess = value
                            thirdGuess = value
                        }
                    case "guess4":
                        if !value.isEmpty {
                            GameModel.shared.fourthGuess = value
                            fourthGuess = value
                        }
                    case "guess5":
                        if !value.isEmpty {
                            GameModel.shared.fifthGuess = value
                            fifthGuess = value
                        }
                    case "guess6":
                        if !value.isEmpty {
                            GameModel.shared.sixthGuess = value
                            sixthGuess = value
                        }
                    default: ()
                    }
                }
            }
            
            gridView?.instantlyCheckAllWords(
                firstGuess: firstGuess,
                secondGuess: secondGuess,
                thirdGuess: thirdGuess,
                fourthGuess: fourthGuess,
                fifthGuess: fifthGuess,
                sixthGuess: sixthGuess)
            GameModel.shared.populateAnswerLetterCountDictionary {}
        }
        
        gridView?.keyboardView?.isUserInteractionEnabled = true
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
        requestPresentationStyle(.compact)
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
        print("didCancelSending(_ message: MSMessage, conversation: MSConversation)")
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

}

extension MessagesViewController: MFMessageComposeViewControllerDelegate {
    func messageComposeViewController(_ controller: MFMessageComposeViewController, didFinishWith result: MessageComposeResult) {
        print("messageComposeViewController(_ controller: MFMessageComposeViewController, didFinishWith result: MessageComposeResult)")
        print("result: \(result)")
    }
}
